### ISSUE TITLE
Implement ServiceNow API

### ISSUE THREAD

**Issue by git-Ball** [snow-environment/snow-environment.github.io#20]

**Comment by karastoyanov** [comment]
- `servicenow-rest-api` implemented with [Async Function](https://github.com/snow-environment/snow-environment.github.io/blob/main/src/lib/servicenowAsync.js)
 - [ServiceNow connector](https://github.com/snow-environment/snow-environment.github.io/blob/main/src/servicenowConn.js) serves at script to establish connection to the ServiceNow instance
 - Credentials are taken from [app.js](https://github.com/snow-environment/snow-environment.github.io/blob/main/src/app.js) where they are stored after the user succesfully login
